name=SWP2P
version=0.0.0
author=Sierrastdio
maintainer=Sierrastdio
sentence=A custom software-based peer-to-peer communication library for AVR.
paragraph=SWP2P allows multi-node communication using shared clock, busy, ack, and data lines with hardware interrupts.
category=Communication
url=https://github.com/Sierrastdio/SWP2P
architectures=avr
includes=SWP2P.h
